disconnect: Return a promise that blocks until the connection closes
protojure/lib pull request #128
Opened 2022-03-17 04:23 UTC by sundbry

### Background
I discovered some race conditions in unit tests I was writing, spinning up servers and clients, making rpcs, and tearing them back down. It turns out that the `disconnect` method here was not blocking until the connection closes. This patch makes a small breaking change to the API, so `disconnect` returns a promise of the context map instead of just the context map. The promise resolves when the HTTP2Client fully shuts down.

Since this is a public API change, even if maybe nobody will notice it, we can either bump the minor version number, or let me know if you want me to rework it into a backwards compatible change (perhaps with a config option to enable returning a promise). Without changing the interface, we can just sync on the promise internally before returning the context. However I think it would be beneficial to return a promise from `disconnect` to be consistent with the `connect` interface. 

### Commit Description
The `.stop` method on the Jetty HTTP2Client is non-blocking. The client
must use an event listener to synchronize the state until the client
completely shuts down.

This changes the interface of the public `(disconnect)` API to return
a promise instead, which will resolve when the HTTP2Client finishes
stopping (or throws on an error).

Signed-off-by: Ryan Sundberg <ryan@arctype.co>

2022-03-17 11:54 UTC, ghaskins commented
Code looks good.  Add yourself to CONTRIBUTORs and I'll get this merged/released.

I'm thinking the breaking change probably doesn't impact anything, as you pointed out.  By definition, it was behaving similarly to failing to deref it before.  Just to be safe, ill bump the minor version with a note.

2022-03-17 12:04 UTC, ghaskins requested changes
Just need to update CONTRIBUTORS

2022-03-18 18:28 UTC, sundbry commented
Done updating CONTRIBUTORS @ghaskins

2022-03-18 18:28 UTC, ghaskins approved these changes
Thank you!

2022-03-18 18:39 UTC, merged

2022-03-18 18:51 UTC, ghaskins commented
Included in [v2.1.0](https://github.com/protojure/lib/releases/tag/v2.1.0)